-- public.sys_parameter definition

-- Drop table

-- DROP TABLE public.sys_parameter;

CREATE TABLE public.sys_parameter (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp DEFAULT now() NOT NULL,
	status varchar DEFAULT 'A'::character varying NOT NULL,
	deleted bool DEFAULT false NOT NULL,
	"name" varchar NOT NULL,
	string_value varchar NULL,
	number_value numeric NULL,
	date_value timestamp NULL,
	bool_value bool NULL,
	config jsonb NULL,
	description varchar NULL,
	CONSTRAINT sys_parameter_pkey PRIMARY KEY (id)
);

alter table "sys_parameter" enable row level security;

create policy "Enable read access for all authenticated users" on "public"."sys_parameter" as permissive for select to authenticated using (true);