-- public.profile_claims definition

-- Drop table

-- DROP TABLE public.profile_claims;

CREATE TABLE public.profile_claims (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp DEFAULT now() NOT NULL,
	updated_at timestamp NULL,
	status varchar DEFAULT 'A'::character varying NOT NULL,
	deleted bool DEFAULT false NOT NULL,
	user_id uuid NOT NULL,
	claim varchar NOT NULL,
	created_by uuid DEFAULT auth.uid() NULL,
	info text NULL,
	CONSTRAINT profile_claims_pkey PRIMARY KEY (id)
);

create policy "Enable insert for users based on user_id" on "public"."profile_claims" as permissive for insert to authenticated with check ((( SELECT uid() AS uid) = user_id));

create policy "Enable read access for own claims" on "public"."profile_claims" as permissive for select to authenticated using ((( SELECT uid() AS uid) = user_id));

create policy "Enable update for users for own profile" on "public"."profile_claims" as permissive for update to authenticated using ((( SELECT uid() AS uid) = user_id));

