-- public.products definition

-- Drop table

-- DROP TABLE public.products;

CREATE TABLE public.products (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	uid int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id uuid DEFAULT auth.uid() NOT NULL,
	tenant_id uuid NOT NULL,
	product_type varchar NOT NULL,
	category_id uuid NOT NULL,
	"name" varchar NULL,
	created_at timestamp DEFAULT now() NOT NULL,
	updated_at timestamp NULL,
	status varchar DEFAULT 'A'::character varying NOT NULL,
	deleted bool DEFAULT false NOT NULL,
	sale_delivery bool DEFAULT false NOT NULL,
	sale_pickup_in_store bool DEFAULT false NOT NULL,
	has_complements bool DEFAULT false NOT NULL,
	has_inventory bool DEFAULT false NOT NULL,
	qtd_inventory int8 DEFAULT '0'::bigint NOT NULL,
	disponibility jsonb NULL,
	description text NULL,
	price numeric NULL,
	cost_price numeric NULL,
	discount numeric NULL,
	discount_percent numeric NULL,
	CONSTRAINT products_pkey PRIMARY KEY (id),
	CONSTRAINT products_uid_key UNIQUE (uid)
);