-- public.config_products_table definition

-- Drop table

-- DROP TABLE public.config_products_table;

CREATE TABLE public.config_products_table (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	uid uuid DEFAULT gen_random_uuid() NULL,
	created_at timestamp DEFAULT now() NOT NULL,
	updated_at timestamp NULL,
	status varchar DEFAULT 'A'::character varying NOT NULL,
	deleted bool DEFAULT false NOT NULL,
	user_id uuid DEFAULT auth.uid() NULL,
	"name" varchar NULL,
	image_url text NULL,
	description text NULL,
	ncm varchar NULL,
	CONSTRAINT config_products_table_pkey PRIMARY KEY (id)
);


alter table "config_products_table" enable row level security;


create policy "Anyone authenticated can select" on "public"."config_products_table" as permissive for select to authenticated using (true);
create policy "Only admin and gestor" on "public"."config_products_table" as permissive for insert to authenticated with check (is_claims_admin());
create policy "Enable update for users based on user_id" on "public"."config_products_table" as permissive for update to authenticated using (is_claims_admin());