-- public.profiles_email_confirmation definition

-- Drop table

-- DROP TABLE public.profiles_email_confirmation;

CREATE TABLE public.profiles_email_confirmation (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp DEFAULT now() NOT NULL,
	update_at timestamp NULL,
	status varchar DEFAULT 'A'::character varying NULL,
	deleted bool DEFAULT false NULL,
	email text NULL,
	code varchar NULL,
	CONSTRAINT profiles_email_confirmation_pkey PRIMARY KEY (id)
);

alter table "profiles_email_confirmation" enable row level security;

create policy "Ano user can insert verification" on "public"."profiles_email_confirmation" as permissive for insert to anon with check (true);