-- public.tb_tickets definition

-- Drop table

-- DROP TABLE public.tb_tickets;

CREATE TABLE public.tb_tickets (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	code UUID DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
	status varchar DEFAULT 'A'::character varying NOT NULL,
	deleted bool DEFAULT false NOT NULL,
	"type" varchar NULL,
	"name" varchar NULL,
	email varchar NULL,
	instagram varchar NULL,
	phone varchar NULL,
	message text NULL,
	readed bool DEFAULT false NULL,
	status_ticket varchar NULL,
	recaptcha varchar NULL,
	CONSTRAINT tb_tickets_pkey PRIMARY KEY (id)
);

alter table "tb_tickets" enable row level security;
