
-- public.lara_store_menu_files definition

-- Drop table

-- DROP TABLE public.lara_store_menu_files;

CREATE TABLE public.lara_store_menu_files (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp DEFAULT now() NOT NULL,
	updated_at timestamp NULL,
	status varchar DEFAULT 'A'::character varying NULL,
	deleted bool DEFAULT false NULL,
	created_by uuid DEFAULT auth.uid() NOT NULL,
	store_id uuid NOT NULL,
	file_path varchar NOT NULL,
	write_status varchar DEFAULT 'REQUESTED'::character varying NOT NULL,
	writed_by uuid NULL,
	writed_at timestamp NULL,
	CONSTRAINT lara_store_menu_files_pkey PRIMARY KEY (id)
);


alter table "lara_store_menu_files" enable row level security;

create policy "Users can send menu files" on "public"."lara_store_menu_files" as permissive for insert to authenticated with check (true);

create policy "Can get tenants stores" on "public"."lara_stores" as permissive for select to authenticated using (public.use_has_tenant(auth.uid(), id));